In [1]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math as math
import glob

In [2]:
df=pd.concat([pd.read_csv(f, compression="gzip", header=None, usecols=[5,6,8,9,12,13,14,15,16,18,19,2]) for f in glob.glob(r"C:\Users\so51713\Documents\GoogleCloudDS\task_usage1\part-00*.csv.gz")])
df.columns=[ 'MeanCPUUsage', 'CanMemUsage','UnmapPCMemUsage','TotalPCMemUsage','MeanLocalDiskUsed','MaxCPUUsage','MaxDIOTime','CPI','MAI','AggType','SamplCPUUsage','JobId']
print(df.shape)

(12210234, 12)


In [3]:
nonEmptyDF=df.dropna()
print(nonEmptyDF.shape)

(10262355, 12)


In [4]:
nonEmptyDF.describe()

MeanCPUUsage   CanMemUsage  UnmapPCMemUsage  TotalPCMemUsage  \
count  1.026236e+07  1.026236e+07     1.026236e+07     1.026236e+07   
mean   5.622761e+09  1.653807e-02     2.006269e-02     2.401548e-03   
std    1.074102e+09  3.516807e-02     3.511301e-02     5.670513e-03   
min    3.418309e+06  0.000000e+00     0.000000e+00     0.000000e+00   
25%    5.402489e+09  2.012000e-04     9.527000e-04     1.822000e-04   
50%    6.221862e+09  1.535000e-03     6.111000e-03     5.379000e-04   
75%    6.238340e+09  1.770000e-02     2.252000e-02     1.497000e-03   
max    6.253231e+09  6.633000e+00     5.820000e-01     2.021000e-01   

       MeanLocalDiskUsed   MaxCPUUsage    MaxDIOTime           CPI  \
count       1.026236e+07  1.026236e+07  1.026236e+07  1.026236e+07   
mean        6.396766e-03  9.288692e-05  6.467424e-02  1.817410e-02   
std         2.496122e-02  2.273780e-04  1.965401e-01  6.689432e-02   
min         0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%         3.710000e-04  1.907000e-06  8.354000e-04  1.431000e-04   
50%         8.898000e-04  2.575000e-05  1.950000e-02  1.358000e-03   
75%         2.155000e-03  1.278000e-04  9.509000e-02  8.286000e-03   
max         2.285000e-01  7.256000e-03  5.370000e+02  1.098000e+01   

                MAI       AggType  SamplCPUUsage         JobId  
count  1.026236e+07  1.026236e+07   1.026236e+07  1.026236e+07  
mean   4.640186e+00  1.628924e-02   2.135487e-01  9.330574e-03  
std    5.327997e+00  2.596727e-02   4.098118e-01  2.786820e-02  
min    6.952000e-02  0.000000e+00   0.000000e+00  0.000000e+00  
25%    1.950000e+00  3.913000e-03   0.000000e+00  5.722000e-06  
50%    3.163000e+00  8.274000e-03   0.000000e+00  1.469000e-04  
75%    4.278000e+00  1.300000e-02   0.000000e+00  2.083000e-03  
max    1.599000e+03  2.000000e+00   1.000000e+00  4.971000e-01

In [5]:
print("No of unique jobs : ",nonEmptyDF.JobId.nunique())

No of unique jobs :  5621


In [6]:
#Define X,Y
X=nonEmptyDF.drop(nonEmptyDF.columns[[7]], axis=1).values
Y=nonEmptyDF.iloc[:,7].values
print(X)
print(Y)

[[1.562e-03 6.787e-02 1.156e-03 ... 7.243e-03 1.000e+00 0.000e+00]
 [1.568e-03 6.787e-02 3.195e-04 ... 5.791e-03 1.000e+00 0.000e+00]
 [3.071e-04 8.044e-02 2.823e-04 ... 2.080e-02 1.000e+00 0.000e+00]
 ...
 [1.364e-04 2.670e-05 0.000e+00 ... 1.064e-03 0.000e+00 0.000e+00]
 [1.460e-02 3.475e-03 1.783e-04 ... 3.184e-03 0.000e+00 2.481e-02]
 [1.488e-02 3.075e-03 2.337e-04 ... 1.176e-03 0.000e+00 3.525e-03]]
[2.445  2.1    5.588  ... 1.067  1.542  0.9734]


In [7]:
# Create training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

# Feature scaling
from sklearn.preprocessing import MinMaxScaler
minMaxScaler_X1 = MinMaxScaler()
X_train = minMaxScaler_X1.fit_transform(X_train)
X_test= minMaxScaler_X1.transform(X_test)

# Perform MLR
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)
Y_pred=regressor.predict(X_test)
print(Y_pred)
print(Y_test)

[ 7.65699158  4.09412136 25.33690994 ...  7.77196781  1.83781083
  1.50846176]
[ 9.775  4.012 24.75  ...  7.473  1.751  1.478]


In [9]:
errors = abs(Y_pred - Y_test)
print('Mean Absolute Error:', round(np.mean(errors), 2))

Mean Absolute Error: 0.41


In [13]:
mape = 100 * (errors / Y_test)
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')
print(np.mean(mape))

Accuracy: 86.03 %.
13.969446226768627


In [6]:
# To view performance
minMaxScaler_X2 = MinMaxScaler()
X_scaled = minMaxScaler_X2.fit_transform(X)
import statsmodels.formula.api as sm
X_new=np.append(arr= np.ones((len(nonEmptyDF),1)).astype(int),values=X_scaled,axis=1)
X_opt=X_new[:, [0,1,2,3,4,5,6,7,8,9,10]]
regressor_ols=sm.OLS(endog=Y,exog=X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                 3.519e+07
Date:                Mon, 26 Nov 2018   Prob (F-statistic):               0.00
Time:                        01:14:57   Log-Likelihood:            -1.3445e+07
No. Observations:            10262355   AIC:                         2.689e+07
Df Residuals:                10262344   BIC:                         2.689e+07
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3823      0.000   3211.131      0.000       1.381       1.383
x1           -20.9087      0.079   -264.847      0.000     -21.063     -20.754
x2             1.4716      0.008    191.199      0.000       1.457       1.487
x3             2.6717      0.018    146.187      0.000       2.636       2.708
x4            -1.1695      0.005   -228.671      0.000      -1.180      -1.159
x5             1.2132      0.010    123.911      0.000       1.194       1.232
x6           -20.5814      0.864    -23.817      0.000     -22.275     -18.888
x7             5.3847      0.051    104.717      0.000       5.284       5.486
x8           402.9102      0.022    1.8e+04      0.000     402.866     402.954
x9            -0.1441      0.001   -169.576      0.000      -0.146      -0.142
x10           -0.6653      0.006   -107.113      0.000      -0.678      -0.653
==================================================================================
Omnibus:                 63931027.460   Durbin-Watson:                       1.617
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   169428654628493792.000
Skew:                         488.197   Prob(JB):                             0.00
Kurtosis:                  629472.965   Cond. No.                         3.18e+03
==================================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.18e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""