In [1]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math as math
import glob

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold

In [2]:
df=pd.concat([pd.read_csv(f, compression="gzip", header=None, usecols=[5,6,7,8,9,10,11,12,13,14,15,16,18,19]) for f in glob.glob(r"C:\Users\so51713\Documents\GoogleCloudDS\task_usage1\part-00*.csv.gz")])
df.columns=[ 'MeanCPUUsage', 'CanMemUsage','AssgnMemUsage','UnmapPCMemUsage','TotalPCMemUsage','MaxMemUsage','MeanDIOTime','MeanLocalDiskUsed','MaxCPUUsage','MaxDIOTime','CPI','MAI','AggType','SamplCPUUsage']
print(df.shape)

(12210234, 14)


In [3]:
nonEmptyDF=df.dropna()
print(nonEmptyDF.shape)

(10262355, 14)


In [4]:
X=nonEmptyDF.drop(nonEmptyDF.columns[[10]], axis=1).values
Y=nonEmptyDF.iloc[:,10].values
print(X)
print(Y)

[[1.562e-03 6.787e-02 7.568e-02 ... 7.243e-03 1.000e+00 0.000e+00]
 [1.568e-03 6.787e-02 7.556e-02 ... 5.791e-03 1.000e+00 0.000e+00]
 [3.071e-04 8.044e-02 9.521e-02 ... 2.080e-02 1.000e+00 0.000e+00]
 ...
 [1.364e-04 2.670e-05 0.000e+00 ... 1.064e-03 0.000e+00 0.000e+00]
 [1.460e-02 3.475e-03 4.517e-03 ... 3.184e-03 0.000e+00 2.481e-02]
 [1.488e-02 3.075e-03 4.005e-03 ... 1.176e-03 0.000e+00 3.525e-03]]
[2.445  2.1    5.588  ... 1.067  1.542  0.9734]


In [5]:
# Create training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

# Feature scaling
from sklearn.preprocessing import MinMaxScaler
minMaxScaler_X1 = MinMaxScaler()
X_train = minMaxScaler_X1.fit_transform(X_train)
X_test= minMaxScaler_X1.transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestRegressor
model1= RandomForestRegressor(n_estimators = 10, random_state = 42)
model1.fit(X_train,Y_train)
Y_pred=model1.predict(X_test)
print(Y_pred)
print(Y_test)

C:\Users\so51713\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


[ 8.69966  4.00603 24.9967  ...  7.14309  1.81979  1.46056]
[ 9.775  4.012 24.75  ...  7.473  1.751  1.478]


In [7]:
errors = abs(Y_pred - Y_test)
print('Mean Absolute Error:', round(np.mean(errors), 2))

Mean Absolute Error: 0.14


In [8]:
mape = 100 * (errors / Y_test)
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 96.86 %.
